# Generated by Django 3.0.8 on 2020-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
