# Generated by Django 3.0.8 on 2020-07-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='listing',
        ),
    ]
